services:

  app:
    build: .
    hostname: app
    depends_on:
      - mongodb
      - redis
    environment:
      - DATABASE_URL=mongodb://temp-root-username:temp-password@mongodb/chat_projetweb?authSource=admin
      - JWT_SECRET=ba63466f102443f4bb6f3670891358bc4488d0c717f6ebcd3ee3c5144e55fe2d
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    build: ./mongodb_rs
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=temp-root-username
      - MONGO_INITDB_ROOT_PASSWORD=temp-password
      - MONGO_INITDB_DATABASE=chat_projetweb
      - MONGO_REPLICA_HOST=mongodb
      - MONGO_REPLICA_PORT=27017
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db/
      - mongo-logs:/var/log/mongodb/
    networks:
      - app_network

  redis:
    image: redis:latest
    hostname: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=temp-redis-password
    volumes:
      - redis-data:/root/redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data:
  mongo-logs:
  redis-data: